server:
  port: 8080

spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
      - id: mall-goods
        uri: lb://mall-goods
        predicates:
        - Path=/goods/**
        filters:
        - StripPrefix=1
      - id: mall-mobile
        uri: lb://mall-mobile
        predicates:
        - Path=/mobile/**
        filters:
        - StripPrefix=1
