server:
  port: 8090

spring:
  application:
    name: mall-platform
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.perenc.mall.mobile.mappper: debug
logging:
  file: F:\wanlvcheng\work project\logs\mall-out.log
